'''

Description:

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.



Example 2:

Input: s = "", t = "y"
Output: "y"



Example 3:

Input: s = "a", t = "aa"
Output: "a"



Example 4:

Input: s = "ae", t = "aea"
Output: "a"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lower-case English letters.

'''


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:

        diff = 0
        
        for char in (s + t):

            # compute the XOR result of ASCII code            
            diff ^= ord(char)
        
        # get the character of difference
        return chr(diff)

# m : the character length of s
# n : the character length of t

## Time Complexity: O( m + n )
#
# The overhead in time is the cost of for-loop iteration, which is of O( m + n )

## Space Complexity: O( m + n )
#
# The overhead in space is the storage for s + t, which is of O( m + n )


import unittest

class Testing( unittest.TestCase ):

    def test_case_1( self ):

        result = Solution().findTheDifference( s = "abcd", t = "abcde" )
        self.assertEqual(result, 'e')


    def test_case_2( self ):

        result = Solution().findTheDifference( s = "", t = "y" )
        self.assertEqual(result, 'y')


    def test_case_3( self ):

        result = Solution().findTheDifference( s = "a", t = "aa" )
        self.assertEqual(result, 'a')


    def test_case_4( self ):

        result = Solution().findTheDifference( s = "ae", t = "aea" )
        self.assertEqual(result, 'a')


if __name__ == '__main__':

    unittest.main()        

